apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
  namespace: expense
spec:
  storageClassName: "ebs-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi